// <auto-generated />
using System;
using DataBision.Infrastructure.Data.Staging;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataBision.Infrastructure.Data.Staging.Migrations
{
    [DbContext(typeof(StagingDbContext))]
    [Migration("20260610202144_AddMartProcessSchemas")]
    partial class AddMartProcessSchemas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataBision.Infrastructure.Data.Staging.Entities.CompanyProcessEnabled", b =>
                {
                    b.Property<string>("CompanyId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("company_id");

                    b.Property<string>("ProcessCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("process_code");

                    b.Property<DateTime>("EnabledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enabled_at_utc");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.HasKey("CompanyId", "ProcessCode")
                        .HasName("pk_company_process_enabled");

                    b.ToTable("company_process_enabled", "cfg");
                });

            modelBuilder.Entity("DataBision.Infrastructure.Data.Staging.Entities.ExtractionRun", b =>
                {
                    b.Property<string>("RunId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("run_id");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("company_id");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at_utc");

                    b.Property<string>("IngestionMode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("ingestion_mode");

                    b.Property<int>("RowsInserted")
                        .HasColumnType("integer")
                        .HasColumnName("rows_inserted");

                    b.Property<int>("RowsReceived")
                        .HasColumnType("integer")
                        .HasColumnName("rows_received");

                    b.Property<int>("RowsSkipped")
                        .HasColumnType("integer")
                        .HasColumnName("rows_skipped");

                    b.Property<int>("RowsUpdated")
                        .HasColumnType("integer")
                        .HasColumnName("rows_updated");

                    b.Property<string>("SapObject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sap_object");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("WatermarkDate")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("watermark_date");

                    b.Property<string>("WatermarkTs")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("watermark_ts");

                    b.HasKey("RunId")
                        .HasName("pk_extraction_run");

                    b.ToTable("extraction_run", "ctl");
                });

            modelBuilder.Entity("DataBision.Infrastructure.Data.Staging.Entities.IngestAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("company_id");

                    b.Property<string>("Detail")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("detail");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("run_id");

                    b.Property<string>("SapObject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sap_object");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_ingest_audit_log");

                    b.ToTable("ingest_audit_log", "audit");
                });

            modelBuilder.Entity("DataBision.Infrastructure.Data.Staging.Entities.IngestCheckpoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("company_id");

                    b.Property<DateTime?>("LastSuccessfulRunUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_successful_run_utc");

                    b.Property<string>("SapObject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sap_object");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("tenant_id");

                    b.Property<long>("TotalRowsIngested")
                        .HasColumnType("bigint")
                        .HasColumnName("total_rows_ingested");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WatermarkDate")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("watermark_date");

                    b.Property<string>("WatermarkTs")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("watermark_ts");

                    b.HasKey("Id")
                        .HasName("pk_ingest_checkpoint");

                    b.HasIndex("TenantId", "CompanyId", "SapObject")
                        .IsUnique()
                        .HasDatabaseName("UX_ingest_checkpoint_tenant_company_object");

                    b.ToTable("ingest_checkpoint", "ctl");
                });

            modelBuilder.Entity("DataBision.Infrastructure.Data.Staging.Entities.SourceObjectConfig", b =>
                {
                    b.Property<string>("SourceObject")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_object");

                    b.Property<string>("AlertEmail")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("alert_email");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("ExtractionMode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("extraction_mode");

                    b.Property<int>("FrequencyMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("frequency_minutes");

                    b.Property<string>("HeaderTable")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("header_table");

                    b.Property<string>("InitialLoadFromDate")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("initial_load_from_date");

                    b.Property<bool>("IsMasterData")
                        .HasColumnType("boolean")
                        .HasColumnName("is_master_data");

                    b.Property<string>("LineTable")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("line_table");

                    b.Property<int>("LookbackMonthCloseDays")
                        .HasColumnType("integer")
                        .HasColumnName("lookback_month_close_days");

                    b.Property<int>("LookbackNightlyDays")
                        .HasColumnType("integer")
                        .HasColumnName("lookback_nightly_days");

                    b.Property<int>("LookbackNormalDays")
                        .HasColumnType("integer")
                        .HasColumnName("lookback_normal_days");

                    b.Property<int>("MaxPerRun")
                        .HasColumnType("integer")
                        .HasColumnName("max_per_run");

                    b.Property<string>("NaturalKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("natural_key");

                    b.Property<int>("PageSize")
                        .HasColumnType("integer")
                        .HasColumnName("page_size");

                    b.Property<string>("PrimaryKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("primary_key");

                    b.Property<int>("RetentionDaysRaw")
                        .HasColumnType("integer")
                        .HasColumnName("retention_days_raw");

                    b.Property<bool>("SupportsCreateTs")
                        .HasColumnType("boolean")
                        .HasColumnName("supports_create_ts");

                    b.Property<bool>("SupportsUpdateTs")
                        .HasColumnType("boolean")
                        .HasColumnName("supports_update_ts");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("SourceObject")
                        .HasName("pk_source_object_config");

                    b.HasIndex("SourceObject")
                        .IsUnique()
                        .HasDatabaseName("UX_source_object_config_object");

                    b.ToTable("source_object_config", "ctl");
                });
#pragma warning restore 612, 618
        }
    }
}
