// <auto-generated />
using System;
using DataBision.Infrastructure.Data.Staging;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataBision.Infrastructure.Data.Staging.Migrations;

[DbContext(typeof(StagingDbContext))]
partial class StagingDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("DataBision.Infrastructure.Data.Staging.Entities.ExtractionRun", b =>
        {
            b.Property<string>("RunId").HasColumnType("nvarchar(36)").HasMaxLength(36);
            b.Property<string>("TenantId").IsRequired().HasColumnType("nvarchar(36)").HasMaxLength(36);
            b.Property<string>("CompanyId").IsRequired().HasColumnType("nvarchar(36)").HasMaxLength(36);
            b.Property<string>("SapObject").IsRequired().HasColumnType("nvarchar(50)").HasMaxLength(50);
            b.Property<string>("IngestionMode").IsRequired().HasColumnType("nvarchar(30)").HasMaxLength(30);
            b.Property<string>("Status").IsRequired().HasColumnType("nvarchar(20)").HasMaxLength(20);
            b.Property<DateTime>("StartedAtUtc").HasColumnType("datetime2");
            b.Property<DateTime?>("FinishedAtUtc").HasColumnType("datetime2");
            b.Property<int>("RowsReceived").HasColumnType("int").HasDefaultValue(0);
            b.Property<int>("RowsInserted").HasColumnType("int").HasDefaultValue(0);
            b.Property<int>("RowsUpdated").HasColumnType("int").HasDefaultValue(0);
            b.Property<int>("RowsSkipped").HasColumnType("int").HasDefaultValue(0);
            b.Property<string>("WatermarkDate").HasColumnType("nvarchar(10)").HasMaxLength(10);
            b.Property<string>("WatermarkTs").HasColumnType("nvarchar(6)").HasMaxLength(6);
            b.Property<string>("ErrorMessage").HasColumnType("nvarchar(2000)").HasMaxLength(2000);
            b.HasKey("RunId").HasName("PK_extraction_run");
            b.ToTable("extraction_run", "ctl");
        });

        modelBuilder.Entity("DataBision.Infrastructure.Data.Staging.Entities.IngestAuditLog", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));
            b.Property<string>("RunId").IsRequired().HasColumnType("nvarchar(36)").HasMaxLength(36);
            b.Property<string>("TenantId").IsRequired().HasColumnType("nvarchar(36)").HasMaxLength(36);
            b.Property<string>("CompanyId").IsRequired().HasColumnType("nvarchar(36)").HasMaxLength(36);
            b.Property<string>("SapObject").IsRequired().HasColumnType("nvarchar(50)").HasMaxLength(50);
            b.Property<string>("EventType").IsRequired().HasColumnType("nvarchar(20)").HasMaxLength(20);
            b.Property<string>("Detail").HasColumnType("nvarchar(4000)").HasMaxLength(4000);
            b.Property<DateTime>("OccurredAtUtc").HasColumnType("datetime2");
            b.HasKey("Id").HasName("PK_ingest_audit_log");
            b.HasIndex("RunId", "TenantId").HasDatabaseName("IX_ingest_audit_log_run_tenant");
            b.ToTable("ingest_audit_log", "audit");
        });

        modelBuilder.Entity("DataBision.Infrastructure.Data.Staging.Entities.IngestCheckpoint", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<string>("TenantId").IsRequired().HasColumnType("nvarchar(36)").HasMaxLength(36);
            b.Property<string>("CompanyId").IsRequired().HasColumnType("nvarchar(36)").HasMaxLength(36);
            b.Property<string>("SapObject").IsRequired().HasColumnType("nvarchar(50)").HasMaxLength(50);
            b.Property<string>("WatermarkDate").HasColumnType("nvarchar(10)").HasMaxLength(10);
            b.Property<string>("WatermarkTs").HasColumnType("nvarchar(6)").HasMaxLength(6);
            b.Property<DateTime?>("LastSuccessfulRunUtc").HasColumnType("datetime2");
            b.Property<long>("TotalRowsIngested").HasColumnType("bigint").HasDefaultValue(0L);
            b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
            b.HasKey("Id").HasName("PK_ingest_checkpoint");
            b.HasIndex("TenantId", "CompanyId", "SapObject").IsUnique().HasDatabaseName("UX_ingest_checkpoint_tenant_company_object");
            b.ToTable("ingest_checkpoint", "ctl");
        });

        modelBuilder.Entity("DataBision.Infrastructure.Data.Staging.Entities.SourceObjectConfig", b =>
        {
            b.Property<string>("SourceObject").HasColumnType("nvarchar(50)").HasMaxLength(50);
            b.Property<bool>("Enabled").HasColumnType("bit").HasDefaultValue(true);
            b.Property<string>("ExtractionMode").IsRequired().HasColumnType("nvarchar(30)").HasMaxLength(30).HasDefaultValue("INCREMENTAL");
            b.Property<int>("FrequencyMinutes").HasColumnType("int").HasDefaultValue(60);
            b.Property<int>("LookbackNormalDays").HasColumnType("int").HasDefaultValue(3);
            b.Property<int>("LookbackNightlyDays").HasColumnType("int").HasDefaultValue(7);
            b.Property<int>("LookbackMonthCloseDays").HasColumnType("int").HasDefaultValue(35);
            b.Property<string>("InitialLoadFromDate").HasColumnType("nvarchar(10)").HasMaxLength(10);
            b.Property<bool>("SupportsUpdateTs").HasColumnType("bit").HasDefaultValue(false);
            b.Property<bool>("SupportsCreateTs").HasColumnType("bit").HasDefaultValue(false);
            b.Property<string>("HeaderTable").HasColumnType("nvarchar(50)").HasMaxLength(50);
            b.Property<string>("LineTable").HasColumnType("nvarchar(50)").HasMaxLength(50);
            b.Property<string>("PrimaryKey").HasColumnType("nvarchar(200)").HasMaxLength(200);
            b.Property<string>("NaturalKey").HasColumnType("nvarchar(200)").HasMaxLength(200);
            b.Property<bool>("IsMasterData").HasColumnType("bit").HasDefaultValue(false);
            b.Property<int>("PageSize").HasColumnType("int").HasDefaultValue(500);
            b.Property<int>("MaxPerRun").HasColumnType("int").HasDefaultValue(10000);
            b.Property<int>("RetentionDaysRaw").HasColumnType("int").HasDefaultValue(90);
            b.Property<string>("AlertEmail").HasColumnType("nvarchar(254)").HasMaxLength(254);
            b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
            b.Property<string>("UpdatedBy").HasColumnType("nvarchar(100)").HasMaxLength(100);
            b.HasKey("SourceObject").HasName("PK_source_object_config");
            b.HasIndex("SourceObject").IsUnique().HasDatabaseName("UX_source_object_config_object");
            b.ToTable("source_object_config", "ctl");
        });
#pragma warning restore 612, 618
    }
}
